
/*
 * APropos.java
 */

package cryptoQuantique;


public class APropos extends javax.swing.JFrame{
	
	public static final long serialVersionUID = 1L;

	/** Creates new form APropos */
    public APropos()
    {
        initComponents();
        labelAPropos.setText(
                "<html><body>" +
                "<center><h2>Simulateur de cryptographie quantique basée sur l'Algorihme BB84.</h2></center><br><p text-align='justify'>" +
                "Développé par Belmamoun Adnane<br>" +
                "dans le cadre d'un projet de Cryptographie<br>" +
                "Projet encadré par Pr. El marraki,PES à la Faculté des Sciences de Rabat.</p><br><center><hr width='60%'><br>" +
                "Master de recherche informatique et télécommunication I.T<br>" +
                 "Master I.T 2010/2011 (premiére année) <br>AUTHEUR: Belmamoun Adnane<br>" +
                "Programme protégé par les droits d'autheur.GSCM LRIT Master I.T 2010/2011.</center>" +
                "</body></html>"
                );
        setLocation(500,250);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        labelAPropos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A propos");
        setResizable(false);

        labelAPropos.setText("La Cryptographie quantique... de la Science Fiction à la Simulaton ");
        labelAPropos.setAlignmentY(0.0F);
        labelAPropos.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        labelAPropos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAPropos, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelAPropos, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APropos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAPropos;
    // End of variables declaration//GEN-END:variables

}
