
/*
 * Parametres.java
 */

package cryptoQuantique;


public class Parametres extends javax.swing.JFrame
{
    public static final long serialVersionUID = 1L;
	/** Creates new form Parametres */
    public Parametres()
    {
        initComponents();
        setLocation(400,300);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        boutonGroupPolar = new javax.swing.ButtonGroup();
        labelEspion = new javax.swing.JLabel();
        labelLois = new javax.swing.JLabel();
        labelPolar = new javax.swing.JLabel();
        boutonParDefaut = new javax.swing.JButton();
        boutonOk = new javax.swing.JButton();
        radioPolar0 = new javax.swing.JRadioButton();
        radioPolar1 = new javax.swing.JRadioButton();
        checkLois = new javax.swing.JCheckBox();
        checkEspion = new javax.swing.JCheckBox();
        labelTraceur = new javax.swing.JLabel();
        checkTrace = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paramétres de la simulation");
        setResizable(false);

        labelEspion.setText("Simuler une écoute espion :");

        labelLois.setText("Respecter les lois physiques :");

        labelPolar.setText("Transcrire les polarisations 0° et 45° en :");

        boutonParDefaut.setText("Par défaut");
        boutonParDefaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonParDefautActionPerformed(evt);
            }
        });

        boutonOk.setText("Ok");
        boutonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOkActionPerformed(evt);
            }
        });

        boutonGroupPolar.add(radioPolar0);
        radioPolar0.setSelected(true);
        radioPolar0.setText("bits à  0");

        boutonGroupPolar.add(radioPolar1);
        radioPolar1.setText("bits à  1");

        checkLois.setSelected(true);

        checkEspion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEspionActionPerformed(evt);
            }
        });

        labelTraceur.setText("Afficher une trace des échanges :");

        checkTrace.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(boutonParDefaut)
                .addGap(18, 18, 18)
                .addComponent(boutonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPolar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioPolar0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioPolar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEspion)
                            .addComponent(labelTraceur)
                            .addComponent(labelLois))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkEspion, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkLois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkTrace)))))
                .addContainerGap(30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEspion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLois, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTraceur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkEspion)
                        .addGap(2, 2, 2)
                        .addComponent(checkLois, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkTrace, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPolar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioPolar0)
                    .addComponent(radioPolar1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonParDefaut)
                    .addComponent(boutonOk))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonParDefautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonParDefautActionPerformed
        // TODO add your handling code here:
        radioPolar0.setSelected(true);
        radioPolar1.setSelected(false);
        checkEspion.setSelected(false);
        checkLois.setSelected(true);
        checkTrace.setSelected(true);
    }//GEN-LAST:event_boutonParDefautActionPerformed

    private void boutonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_boutonOkActionPerformed

    private void checkEspionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEspionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEspionActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametres().setVisible(true);
            }
        });
    }

    public boolean espionChecked()
    {
        return checkEspion.isSelected();
    }
    
    public boolean traceChecked()
    {
        return checkTrace.isSelected();
    }

    public boolean loisChecked()
    {
        return checkLois.isSelected();
    }

    public int polar0_45()
    {
        if(radioPolar0.isSelected())
        {
            return 0;
        }
        
        return 1;
    }

    public void setTraceurOff()
    {
        checkTrace.setSelected(false);

        return;
    }
    
    public int polar90_135()
    {
        if(radioPolar1.isSelected())
        {
            return 0;
        }

        return 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup boutonGroupPolar;
    private javax.swing.JButton boutonOk;
    private javax.swing.JButton boutonParDefaut;
    private javax.swing.JCheckBox checkEspion;
    private javax.swing.JCheckBox checkLois;
    private javax.swing.JCheckBox checkTrace;
    private javax.swing.JLabel labelEspion;
    private javax.swing.JLabel labelLois;
    private javax.swing.JLabel labelPolar;
    private javax.swing.JLabel labelTraceur;
    private javax.swing.JRadioButton radioPolar0;
    private javax.swing.JRadioButton radioPolar1;
    // End of variables declaration//GEN-END:variables

}
